import Head from 'next/head'
import Image from 'next/image'
import gql from 'graphql-tag';
import styles from '../styles/Home.module.css'
import { useQuery } from '@apollo/react-hooks';

const SINGLE_CHARACTER_QUERY = gql`
  query SINGLE_CHARACTER_QUERY($name: String!){
    characters(where: {name: $name}){
      name,
      description,
      appearances {
          name,
          released_date,
      }
    }
  }
`

export default function Home() {
  const name = 'Link'
  const {data, loading, error} = useQuery(SINGLE_CHARACTER_QUERY, {
    variables: {
      name,
    }
  });
  if (error) return console.error(error)
  if (loading) return <p>Loading... </p>
  const { Product } = data
  console.log(Product);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
